name: circle_translate

# Controls when the workflow will run
on:

  schedule:
   - cron: '0 */3 * * *'
  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:

# 工作流运行由一个或多个作业组成，这些作业可以按顺序或并行运行
jobs:
  # 此工作流包含一个名为“build”的作业
  build:
    # 运行作业的运行器类型
    runs-on: ubuntu-latest

    # 步骤表示将作为作业的一部分执行的一系列任务
    steps:
      # 在 $GITHUB_WORKSPACE 下签出存储库，以便作业可以访问它
      - uses: actions/checkout@v4  
        with:
          token: ${{ secrets.WORK_TOKEN }}
    
      - name: Set up Python 
        uses: actions/setup-python@v3  
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev  # 安装libxml2和libxslt开发包
          python -m pip install --upgrade pip
          pip install mtranslate
          pip install lxml
          pip install html5lib
          pip install jinja2
          pip install googletrans
          pip install googletrans==4.0.0-rc1 bs4
          pip install beautifulsoup4 pygtrans feedparser rfeed
          pip install --upgrade feedparser
          pip install requests
      - name: ls_show
        run: |
          python my-mtranslate.py
          ls -al rss/
             
      - name: Push changes to remote repository
        env:
          U_NAME: ${{ secrets.U_NAME }}
          U_EMAIL: ${{ secrets.U_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.WORK_TOKEN }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
          pwd
          git config --local user.name "${U_NAME}"  # 修改name
          git config --local user.email "${U_EMAIL}"  # 修改email

          git status -s
          git add rss/*
          git add test.ini
          git add .github/workflows/circle_translate.yml
          git add README.md

          export TZ='Asia/Shanghai' # 更改时区
          git commit -m "Github RSS Translate Auto Builder at `date +'%Y-%m-%d %H:%M'`"  # 提交记录包含时间 跟上面更改时区配合

          echo "======git push===="
          git push --force origin main
          else
          echo "No changes, skip push."
          fi